name: Gatsby Auto-Publish

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: enriikke/gatsby-gh-pages-action@2.1.1
      with:
        # A personal access token needed to push your site after it has been built.
        access-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-branch: gh-pages
